#!/bin/bash

function get_dependencies() {
    for dep in xenapi-in-the-cloud remote-bash; do
        if [ -e $dep ]; then
            ( cd $dep; git pull; )
        else
            git clone https://github.com/citrix-openstack/$dep
        fi

        if [ -e "$dep/bin" ]; then
            export PATH=$PATH:$(pwd)/$dep/bin
        fi

    done
}
